name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key_files: /Documents/id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
        
         
    
