name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
