name: deploy
on: [push]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          LASTSSH: "Doing something after copying"
        with:
            host: 192.168.1.21
            user: test
            pass: azerty
            scp: |
              './test/*' => /home/test/test1
          
