name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ SSH_PRIVATE_KEY }}
        known_hosts: ${{ KNOWN_HOSTS }}
        
        
         
    
