name: deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Connect to server
      uses: Meijer/ssh-action@master
      with:
        host: 192.168.1.21
        username: myuser
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo mkdir /home/test/reussi
