name: deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sshpass-scp commands
        uses: youxingz/sshpass-scp-action@v3
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          src: ./**
          dist: /usr/local/release
